import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

public class mhsGUI extends javax.swing.JFrame {
    public mhsGUI() {
        initComponents();
        load_table();
        kosong();
    }
    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Stambuk");
        model.addColumn("Nama");
        model.addColumn("Jurusan");
        model.addColumn("Fakultas");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from tabel_mahasiswa";
            java.sql.Connection conn=(Connection)koneksiDb.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            tab1.setModel(model);
        } catch (Exception e) {
        }
        }
    private void kosong(){
        txtnim.setText(null);
        txtnama.setText(null);
        pro.setSelectedItem(this);
        txtfak.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtfak = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        pro = new javax.swing.JComboBox<>();
        smpn2 = new javax.swing.JButton();
        smpn3 = new javax.swing.JButton();

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 82, 240));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("INPUT DATA MAHASISWA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 400, 34));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel2.setText("STAMBUK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 31));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 41, 31));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel4.setText("FAKULTAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 65, 31));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel5.setText("JURUSAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 31));
        getContentPane().add(txtnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 250, 31));

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 250, 31));
        getContentPane().add(txtfak, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 250, 31));

        tab1.setAutoCreateRowSorter(true);
        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab1.setEnabled(false);
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 370, 90));

        pro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi" }));
        pro.setName(""); // NOI18N
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        getContentPane().add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 250, 31));

        smpn2.setText("ADD");
        smpn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpn2ActionPerformed(evt);
            }
        });
        getContentPane().add(smpn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, 33));

        smpn3.setText("SAVE");
        smpn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpn3ActionPerformed(evt);
            }
        });
        getContentPane().add(smpn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proActionPerformed

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        // TODO add your handling code here:                                     
        // menampilkan data kedalam form pengisian:
        int baris = tab1.rowAtPoint(evt.getPoint());
        String nomhs =tab1.getValueAt(baris, 1).toString();
        txtnim.setText(nomhs);
        String nama = tab1.getValueAt(baris,2).toString();
        txtnama.setText(nama);
        String jurusan = tab1.getValueAt(baris,2).toString();
        txtfak.setText(jurusan);
        String prodi = tab1.getValueAt(baris, 3).toString();
        pro.setSelectedItem(prodi);
    }//GEN-LAST:event_tab1MouseClicked

    private void smpn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smpn2ActionPerformed

    private void smpn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smpn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mhsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mhsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mhsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mhsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mhsGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> pro;
    private javax.swing.JButton smpn2;
    private javax.swing.JButton smpn3;
    private javax.swing.JTable tab1;
    private javax.swing.JTextField txtfak;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    // End of variables declaration//GEN-END:variables
}
